name: Validate with hassfest and HACS

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"

#      - name: HACS Action
#        if: "github.ref == 'main' || github.base_ref == 'main'"
#        uses: "hacs/action@main"
#        with:
#          category: "integration"
